image: node:12.13.0

variables:
    PUBLIC_URL: "/job-career"

pages:
  cache:
    paths:
      - jobseeker-ui/node_modules/
  stage: deploy
  script:
    - mkdir public
    - cd jobseeker-ui
    - npm install
    - npm run build
    - mv public/* ../public
    - mv build/* ../public
    - cp ../public/index.html ../public/404.html
  artifacts:
    paths:
      - public
  only:
    - development
    
