image: node:12.13.0
 
pages:
  cache:
    paths:
      - jobseeker-ui/node_modules/
  stage: deploy
  script:
    - mkdir public
    - cd jobseeker-ui
    - npm install
    - npm run build
    - mv public/* ../public
    - mv build/* ../public
  artifacts:
    paths:
      - public
  only:
    - development-ui
