image: node:12.13.0
 
pages:
  cache:
    paths:
      - jobseeker-ui/node_modules/
 
  stage: deploy
  script:
    - cd jobseeker-ui
    - npm install
    - npm run build
    - mv build/* public/
  artifacts:
    paths:
      - jobseeker-ui/public
  only:
    - development-ui
